"""gameplay + inorganic + organic tables

Revision ID: 0002_gameplay_tables
Revises: 0001_auth_tables
Create Date: 2026-08-17

Sinh bang `alembic revision --autogenerate`, da ra soat tay. Autogenerate lan nay
giu dung ca partial index `ix_game_run_leaderboard` lan cac CHECK constraint.
Bo sung thu cong: FK `player_settings.track_id -> music_track.id` (bang music_track
den migration nay moi ton tai nen 0001 chua the khai bao).
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002_gameplay_tables'
down_revision: str | None = '0001_auth_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ion',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('charge', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('polyatomic', sa.Boolean(), nullable=False),
    sa.Column('acid_name', sa.Text(), nullable=True),
    sa.CheckConstraint("type IN ('cation', 'anion')", name='ck_ion_type'),
    sa.CheckConstraint('charge BETWEEN 1 AND 3', name='ck_ion_charge'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isomer',
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('carbons', sa.SmallInteger(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('iupac_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('canonical_key')
    )
    op.create_index('ix_isomer_carbons', 'isomer', ['carbons'], unique=False)
    op.create_table('music_track',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compound',
    sa.Column('cation_id', sa.Text(), nullable=False),
    sa.Column('anion_id', sa.Text(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('cat_sub', sa.SmallInteger(), nullable=False),
    sa.Column('an_sub', sa.SmallInteger(), nullable=False),
    sa.Column('total', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("type IN ('axit', 'base', 'muoi', 'oxit')", name='ck_compound_type'),
    sa.CheckConstraint('total = cat_sub + an_sub', name='ck_compound_total'),
    sa.ForeignKeyConstraint(['anion_id'], ['ion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cation_id'], ['ion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cation_id', 'anion_id')
    )
    op.create_table('game_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'playing'"), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('score_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('client_version', sa.Text(), nullable=False),
    sa.CheckConstraint("mode IN ('inorganic', 'organic')", name='ck_game_run_mode'),
    sa.CheckConstraint("status IN ('playing', 'finished', 'abandoned')", name='ck_game_run_status'),
    sa.CheckConstraint('score >= 0', name='ck_game_run_score'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_run_leaderboard', 'game_run', ['mode', 'score'], unique=False, postgresql_where=sa.text("status = 'finished' AND score_verified"))
    op.create_index('ix_game_run_player', 'game_run', ['player_id', 'started_at'], unique=False)
    op.create_table('player_compound_stat',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('cation_id', sa.Text(), nullable=False),
    sa.Column('anion_id', sa.Text(), nullable=False),
    sa.Column('times_made', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_made_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_made_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cation_id', 'anion_id'], ['compound.cation_id', 'compound.anion_id'], name='fk_player_compound_stat_compound'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'cation_id', 'anion_id')
    )
    op.create_table('run_inorganic',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('level_reached', sa.SmallInteger(), nullable=False),
    sa.Column('compounds_made', sa.SmallInteger(), nullable=False),
    sa.Column('rows_dropped', sa.SmallInteger(), nullable=False),
    sa.Column('grids_cleared', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['game_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('run_organic',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('carbons', sa.SmallInteger(), nullable=False),
    sa.Column('found_count', sa.SmallInteger(), nullable=False),
    sa.Column('total_count', sa.SmallInteger(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('end_reason', sa.Text(), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_run_organic_difficulty'),
    sa.CheckConstraint("end_reason IN ('timeout', 'complete')", name='ck_run_organic_end_reason'),
    sa.ForeignKeyConstraint(['run_id'], ['game_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('run_compound',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('cation_id', sa.Text(), nullable=False),
    sa.Column('anion_id', sa.Text(), nullable=False),
    sa.Column('gained', sa.SmallInteger(), nullable=False),
    sa.Column('dropped', sa.SmallInteger(), nullable=False),
    sa.Column('at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cation_id', 'anion_id'], ['compound.cation_id', 'compound.anion_id'], name='fk_run_compound_compound'),
    sa.ForeignKeyConstraint(['run_id'], ['run_inorganic.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_compound_seq')
    )
    op.create_index('ix_run_compound_run', 'run_compound', ['run_id'], unique=False)
    op.create_table('run_ion_choice',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('ion_id', sa.Text(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ion_id'], ['ion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['run_inorganic.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'ion_id')
    )
    op.create_table('run_isomer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('gained', sa.SmallInteger(), nullable=False),
    sa.Column('bonus', sa.SmallInteger(), nullable=False),
    sa.Column('at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_key'], ['isomer.canonical_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['run_organic.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'canonical_key', name='uq_run_isomer_key'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_isomer_seq')
    )
    # ### end Alembic commands ###

    op.create_foreign_key(
        'fk_player_settings_track',
        'player_settings',
        'music_track',
        ['track_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint('fk_player_settings_track', 'player_settings', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_isomer')
    op.drop_table('run_ion_choice')
    op.drop_index('ix_run_compound_run', table_name='run_compound')
    op.drop_table('run_compound')
    op.drop_table('run_organic')
    op.drop_table('run_inorganic')
    op.drop_table('player_compound_stat')
    op.drop_index('ix_game_run_player', table_name='game_run')
    op.drop_index('ix_game_run_leaderboard', table_name='game_run', postgresql_where=sa.text("status = 'finished' AND score_verified"))
    op.drop_table('game_run')
    op.drop_table('compound')
    op.drop_table('music_track')
    op.drop_index('ix_isomer_carbons', table_name='isomer')
    op.drop_table('isomer')
    op.drop_table('ion')
    # ### end Alembic commands ###
